### PR TITLE
TypeScript to MLscript

### PR DESCRIPTION
**Pull request by NeilKleistGao**

### CODE REVIEW

**Comment by NeilKleistGao** [comment]
<del>The behavior of git diff-files is a little bit weird. It just returned 1 but left nothing about which file was different:</del>
```
Run git diff-files -p --exit-code
  git diff-files -p --exit-code
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_8.0.345_x64: /opt/hostedtoolcache/jdk/8.0.345/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.345/x64
    JAVA_HOME_8_0_345_X64: /opt/hostedtoolcache/jdk/8.0.345/x64
Error: Process completed with exit code 1.
```

<del>by the way, adding `-w` can solve it.</del>
done by adding check before writing.

**Comment by NeilKleistGao** [comment]
And I guess I need to add more comments to explain the logic in `TSSourceFile.scala` but I have got no idea yet.

**Comment by LPTK** [comment]
Thanks for the PR. Before we proceed, please:
* Review your own diff in detail and make sure it's clean (at https://github.com/hkust-taco/mlscript/pull/129/files).
* Read https://github.com/hkust-taco/mlscript/blob/mlscript/CONTRIBUTING.md
* Resolve the conflicts with the main branch (by merging the `mlscript` branch into your branch). (Note that merge conflicts in test files can be automatically resolved by the test command.)

**Comment by NeilKleistGao** [comment]
This just happened again:dizzy_face:
```
Run git diff-files -p --exit-code
  git diff-files -p --exit-code
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_8.0.345_x64: /opt/hostedtoolcache/jdk/8.0.345/x64
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.345/x64
    JAVA_HOME_8_0_345_X64: /opt/hostedtoolcache/jdk/8.0.345/x64
Error: Process completed with exit code 1.
```

**Pull request closed without merging**
