### PR TITLE
Implement multi-parameter functions

### PR DESCRIPTION
**Pull request by LPTK**
This is not yet ready to merge, as the JS code-gen is broken. @chengluyu said he'd have a look and fix it.

### CODE REVIEW

**Comment by chengluyu** [comment]
I’m considering rebase this branch to the latest `mlscript` branch because I have to write old code so I can create a PR against this branch.

**Comment by LPTK** [comment]
@chengluyu Okay I'll be working on it tomorrow. It's quite a tricky rebase.

**Comment by chengluyu** [comment]
> @chengluyu Okay I'll be working on it tomorrow. It's quite a tricky rebase.

Thanks, I tried to understand the changes but failed to finish the rebase yesterday.

**Comment by LPTK** [comment]
Done. The trickiest part, besides the hairy conflicts, was that the new feature of methods needed to be adapted too.

**Pull request merged**
