### PR TITLE
Improve self-type handling

### PR DESCRIPTION
**Pull request by LPTK**
This PR fixes various issues with the handling of self types and adds self-type checking.
As a byproduct, it makes class constructors return proper type refs, which has the welcome benefit of simplifying some inferred recursive types by tying the knot earlier!

To deal with:
 - [x] Fix transitivity problems (see end of ClassSignatures.mls)
 - [x] Add warning when non-abstract class has an annot (did you mean to use `extends`?)

### CODE REVIEW

**Review by NeilKleistGao — COMMENTED** [review]
I think we need a check for this:
```ts
abstract class Foo(): Foo
//│ /!!!\ Uncaught error: java.lang.StackOverflowError

abstract class Bar(): Bar | Bar
//│ /!!!\ Uncaught error: java.lang.StackOverflowError
```

**Comment by LPTK** [comment]
@NeilKleistGao Wow, nice catch! Funnily the SOF happened in type simplification. It was an easy fix.

**Review by NeilKleistGao — APPROVED** [review]
LGTM.

**Comment by LPTK** [comment]
Thanks for the quick review!

**Pull request merged**
